services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: snipbox
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: reshi
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  web:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      DJANGO_SECRET_KEY: django-insecure-pa6*dg7k+mvjbh+@$^+rehi9(o!5_p6py&j&i2nl=odh$3v-=%
      DEBUG: True
      DATABASE_NAME: snipbox
      DATABASE_USER: postgres
      DATABASE_PASSWORD: reshi
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    volumes:
      - .:/app
    ports:
      - "8000:8000"

volumes:
  pgdata:
